If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [25]:
tsum = 0
for x in range(1000):
    if (x % 3 == 0 or x % 5 == 0):
            tsum = tsum + x
print tsum

233168

In [9]:
t_sum = 0
for i in range(1,1000):
    if (i% 3 == 0 or i% 5 == 0):
        t_sum = t_sum + i
print t_sum

233168

In [8]:
total_sum = 0
for i in range(1, 1000):
    if (i % 3 == 0 or i % 5 == 0):
        total_sum = total_sum + i
print total_sum

233168

In [44]:
# 1 to 1000 there are 999 numbers so N=999
N=999

# Get the upper bounds for the arithmetic series
Three = N // 3
Five = N // 5

# 3 times 5 is 15, this means that this is the maximum 
# amount of numbers that are multiples of 3 and 5
Fifteen = N // 15

# sums
sumT = 3*Three*(1 + Three) / 2
sumF = 5*Five*(1 + Five) / 2
sumFif = 15*Fifteen*(1 + Fifteen) / 2

# total
total = sumT + sumF - sumFif

print(total)

233168

In [53]:
import numpy as np
nums = np.arange(999)
three = (nums % 3 == 0)
five = (nums % 5 == 0)
fif = (nums % 15 == 0)
good = np.logical_or(three,five)
np.sum(nums)

498501

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [29]:
n_p, n_c = 0, 1
total = 0
while True:
    n_p , n_c = n_c , n_p + n_c
    if n_c >= 4000000:
        break
    if n_c % 2 == 0:
        total += n_c
print (total)

4613732

In [41]:
even, odd = 0,1
# fibonacci sequence starts at 0 (an even #)
# and 1 (an odd #)
total = 0
# start at 0
while True:
    odd_n = even + odd
    # odd_n is the new odd value 0+1=1 (another odd #)
    even = odd + odd_n 
    # even numbers change when adding odd and odd_n
    # 1+1=2 (an even #)
    if even < 4000000:
        # loop until even numbers is less than 4000000 (until 4000000) 
        total += even
        # add to total all the even values
        odd = odd_n + even               
        # odd is continueally changing in loop by adding previous #'s
    else:
    # while not true then break the loop
        break
print total

4613732

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?