If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
tsum = 0
for x in range(1000):
    if (x % 3 == 0 or x % 5 == 0):
            tsum = tsum + x
print tsum

233168

In [2]:
t_sum = 0
for i in range(1,1000):
    if (i% 3 == 0 or i% 5 == 0):
        t_sum = t_sum + i
print t_sum

233168

In [3]:
total_sum = 0
for i in range(1, 1000):
    if (i % 3 == 0 or i % 5 == 0):
        total_sum = total_sum + i
print total_sum

233168

In [4]:
# 1 to 1000 there are 999 numbers so N=999
N=999

# Get the upper bounds for the arithmetic series
Three = N // 3
Five = N // 5

# 3 times 5 is 15, this means that this is the maximum 
# amount of numbers that are multiples of 3 and 5
Fifteen = N // 15

# sums
sumT = 3*Three*(1 + Three) / 2
sumF = 5*Five*(1 + Five) / 2
sumFif = 15*Fifteen*(1 + Fifteen) / 2

# total
total = sumT + sumF - sumFif

print(total)

233168

In [5]:
import numpy as np
nums = np.arange(999)
three = (nums % 3 == 0)
five = (nums % 5 == 0)
good = np.logical_or(three,five)
np.sum(nums)

498501

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [6]:
n_p, n_c = 0, 1
total = 0
while True:
    n_p , n_c = n_c , n_p + n_c
    if n_c >= 100:
        break
    if n_c % 2 == 0:
        total += n_c
print (total)

44

In [7]:
n_p, n_c = 0, 1
total = 0
while True:
    n_p , n_c = n_c , n_p + n_c
    if n_c >= 4000000:
        break
    if n_c % 2 == 0:
        total += n_c
print (total)

4613732

In [8]:
even, odd = 0,1
# fibonacci sequence starts at 0 (an even #)
# and 1 (an odd #)
total = 0
# start at 0
while True:
    odd_n = even + odd
    # odd_n is the new odd value 0+1=1 (another odd #)
    even = odd + odd_n 
    # even numbers change when adding odd and odd_n
    # 1+1=2 (an even #)
    if even < 4000000:
        # loop until even numbers is less than 4000000 (until 4000000) 
        total += even
        # add to total all the even values
        odd = odd_n + even               
        # odd is continueally changing in loop by adding previous #'s
    else:
    # while not true then break the loop
        break
print total

4613732

In [9]:
a, b = 1, 1
total = 0
while a <= 4000000:
    if a % 2 == 0:
        total += a
    a, b = b, a+b  
    # the real formula for Fibonacci sequence
print total

4613732

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [10]:
num = 600851475143  
i = 2  
while i * i < num:  
     while num % i == 0:  
         num = num / i  
     i = i + 1  
print(num)

6857

In [11]:
n = 20 
i = 2

while i * i < n:
    while n%i == 0:
        n = n / i
    i = i + 1
'''''
This explanation uses two while loops. 
The biggest thing to remember about while loops
is that they run until they are no longer true.

The outer loop states that while i * i isn't greater than n 
(because the largest prime factor will never be larger than 
the square root of n), add 1 to i after the inner loop runs.

The inner loop states that while i divides evenly into n, 
replace n with n divided by i.
This loop runs continuously until it is no longer true. 
For n=20 and i=2, n is replaced by 10, then again by 5. 
Because 2 doesn't evenly divide into 5, the loop stops with n=5 and 
the outer loop finishes, producing i+1=3.

Finally, because 3 squared is greater than 5,
the outer loop is no longer true and prints the result of n.
'''''
print (n)

5

In [12]:
n = 13195 
i = 2

while i * i < n:
    while n%i == 0:
        n = n / i
    i = i + 1

print (n)

29

In [13]:
n = 3098563
i = 2

while i * i < n:
    while n%i == 0:
        n = n / i
    i = i + 1
    
print (n)

8219

In [16]:
from sympy import primefactors
print primefactors(600851475143)[-1]
print primefactors(600851475143)
print primefactors(13195)

6857
[71, 839, 1471, 6857]
[5, 7, 13, 29]